// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  big: string;
  icon_name: string;
  item: string;
  name: string;
  search_input: string;
  selected: string;
  small: string;
  token_list: string;
}
export const cssExports: CssExports;
export default cssExports;
