// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chart: string;
  chart_container: string;
  chart_title: string;
  current_trigger: string;
  data_info: string;
  dot: string;
  drop_menu: string;
  trigger: string;
  trigger_wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
