// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  box: string;
  btn: string;
  coin: string;
  container: string;
  create_content: string;
  desc: string;
  done_btn: string;
  edit: string;
  finish_desc: string;
  finish_logo: string;
  finish_title: string;
  full_name: string;
  info: string;
  input: string;
  input_result: string;
  input_wrap: string;
  label: string;
  line: string;
  name: string;
  no: string;
  steps: string;
  sub_title: string;
  switch_icon: string;
  symbol: string;
  title: string;
  token_info: string;
  token_name: string;
}
export const cssExports: CssExports;
export default cssExports;
