// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  amount: string;
  app_hide: string;
  app_start_btn: string;
  app_title: string;
  box: string;
  btn: string;
  close: string;
  container: string;
  container_center: string;
  content: string;
  current: string;
  desc: string;
  farm_intro: string;
  head: string;
  icon: string;
  item: string;
  item_data: string;
  item_detail_line_2: string;
  item_header: string;
  item_title: string;
  label: string;
  left: string;
  left_inner: string;
  link: string;
  lp_amount: string;
  main_title: string;
  menu: string;
  menu_item: string;
  menu_item_selected: string;
  mod: string;
  mod_content: string;
  name: string;
  right: string;
  right_box: string;
  sidebar: string;
  strong: string;
  subtitle: string;
  symbol: string;
  title: string;
  txid: string;
  txt: string;
  value: string;
}
export const cssExports: CssExports;
export default cssExports;
