// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  arrow: string;
  balance: string;
  box: string;
  btn: string;
  btn_wait: string;
  btn_warn: string;
  can_click: string;
  coin: string;
  container: string;
  content: string;
  detail_close: string;
  detail_item: string;
  detail_title: string;
  done_btn: string;
  finish_desc: string;
  finish_logo: string;
  finish_title: string;
  head: string;
  icon: string;
  input: string;
  item_label: string;
  item_value: string;
  key_value: string;
  line: string;
  menu: string;
  menu_item: string;
  menu_item_selected: string;
  my_pair_info: string;
  name: string;
  normal: string;
  selectToken_wrap: string;
  switch_icon: string;
  title: string;
  tol: string;
  view_detail: string;
}
export const cssExports: CssExports;
export default cssExports;
