// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  app_hide: string;
  app_start_btn_wrap: string;
  app_title: string;
  big_btn: string;
  box: string;
  close: string;
  container: string;
  container_center: string;
  content: string;
  desc: string;
  first: string;
  first_title: string;
  head: string;
  left: string;
  left_inner: string;
  link: string;
  main_title: string;
  menu: string;
  menu_item: string;
  menu_item_selected: string;
  name: string;
  right: string;
  sidebar: string;
  small_btn: string;
  strong: string;
  subtitle: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
